version: '3'

services:
  postgres:
    image: postgis/postgis:10-3.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: payment
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
