version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17

    steps:
      - run:
          name: Start Docker Compose
          command: |
            docker-compose up -d

workflows:
  continuous-integration:
    jobs:
      - build
